### ISSUE TITLE
RuntimeError: Decompression 'SNAPPY' not available

### ISSUE THREAD

**Issue by iReprogram** [nanoporetech/Pore-C-Snakemake#10]
Running snakemake from Ubuntu 18.04 (on Windows Subsystem Linux) w/ 32GB of RAM
Output from: snakemake --use-conda --cores $N
(crashes during step 5 of 11)

Error in rule create_alignment_table:
    jobid: 6
    output: results/align_table/DpnII_run01_GRCh38.at.catalog.yaml, results/align_table/DpnII_run01_GRCh38.at.alignment.parquet, results/align_table/DpnII_run01_GRCh38.at.read.parquet, results/align_table/DpnII_run01_GRCh38.at.overlap.parquet, results/align_table/DpnII_run01_GRCh38.at.alignment_summary.csv, results/align_table/DpnII_run01_GRCh38.at.read_summary.csv
    log: results/logs/results/align_table/DpnII_run01_GRCh38.at.catalog.yaml.log (check log file(s) for error message)
    shell:
        set +u; source ~/miniconda3/etc/profile.d/conda.sh ; conda activate ; conda activate poreC;  pore_c alignments parse results/mapping/DpnII_run01_GRCh38.read_sort.bam results/virtual_digest/DpnII_GRCh38.vd.catalog.yaml results/align_table/DpnII_run01_GRCh38.at -n 5 2>results/logs/results/align_table/DpnII_run01_GRCh38.at.catalog.yaml.log
        (exited with non-zero exit code)

Error Message for yaml.log file:
compression.py", line 128, in decompress_data
    (algorithm.upper(), sorted(decompressions)))
RuntimeError: Decompression 'SNAPPY' not available.  Options: ['BROTLI', 'GZIP', 'UNCOMPRESSED']

**Comment by aboyle** [comment]
Same problem - you can fix this by installing python-snappy in the poreC conda environment:

`conda activate poreC`
`conda install python-snappy`

**Comment by eharr** [comment]
@iReprogram did @aboyle's suggestion fix this for you? If not please try the latest version of the pipeline and pore-c tools - they should have fixed some of the installation issues.
