### ISSUE TITLE
[lh3/bwa] bwa bwasw crashed with the error '[vfprintf(stdout)] Value too large for defined data type' 

### ISSUE THREAD

**Issue by dexon9109** [nanoporetech/Pore-C-Snakemake#11]
Dear author,

In `porec-snakemake`, BWA was used to compare the enzymatic fragment, as shown below:
```
bwa bwasw -b 5 -q 2 -r 1 -T 15 -z 10 -t 30 rg.fa.gz DpnII_run01.rd.pass.fq.gz > out.bam
```
But he made a mistake, I guess because of the length of the original data,
```
#========= 1.log =========#
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[bsw2_aln] read 212828 sequences/pairs (300001648 bp) ...
[bsw2_aln] read 210194 sequences/pairs (300000077 bp) ...
[bsw2_aln] read 207978 sequences/pairs (300002324 bp) ...
[vfprintf(stdout)] Value too large for defined data type
```
Therefore, I don't have a good way to analyze it. At present, I am considering using Minimap2 to replace BWA.However, The BAM of Minimap2 is not supported by Porec-Tools.I'm a little confused now.

I want to hear your opinion. It's really important to me!

Thank u~

**Comment by eharr** [comment]
Hi,

Unfortunately bwa seems to struggle with very long PoreC reads. The workaround that we've been using is to remove reads longer than 100kb (you can use the seqkit tool for this: https://bioinf.shenwei.me/seqkit/usage/#seq). I'm working on an updated version of the pipeline that does this by default but for you you'll have to run it manually.

All the best,
Eoghan

**Comment by dexon9109** [comment]
Actually, I have one more question, I used this `snakemake`+`SALSA2` before.However, SALSA2 does not mount well and cannot be manually mounted and purge using `Juciebox`.
     1. So I finishing an [.assembly] file, but it didn't work(import map assembly in Juciebox).
     2. This heat map of [.hic] in Juciebox is one for each group, as shown below:          

![image](https://user-images.githubusercontent.com/70323837/98184334-1cb8a700-1f45-11eb-957e-e5263f8edd18.png)

Others：

![image](https://user-images.githubusercontent.com/70323837/98184719-019a6700-1f46-11eb-87bf-aaa656fdb4ba.png)


I'd like to replace the mount software, like 3D-DNA and ALL-HIC.However, PoreC-Tools does not output the [.mnd] (long Format) file(only output medium format).
In order to manually correct my mount results, I do not know what to do.
Looking forward to your reply,Please feel free to contact.
Thank u~~
