### ISSUE TITLE
Standard for good experiment

### ISSUE THREAD

**Issue by sachingadakh** [nanoporetech/Pore-C-Snakemake#2]
Hello,
  We have received the results by employing Pore-C pipeline. Yet, we are concerned about the standard of our results whether they are optimum enough or not. Can you guide us regarding the expected / standard % of summary data w.r.t contact order distribution for a good experiment so we can assess our experiment's outcome accordingly?
   Please let me know if you want me to share our results, I can our results by email with my PI's permission. Thank you.

**Comment by eharr** [comment]
Hi @sachingadakh - would you mind moving this question the Nanopore Community website, it's a better place to get support on the protocol itself (beyond the informatics). It would be helpful if you included information on the enzyme you used, the read N50, the contacts/Gb along with the sample you're working on (if possible).

**Comment by sachingadakh** [comment]
Hello Eoghan Harrington sir,
  As per your earlier suggestion in the above thread, I did post my query about 'Standard for good experiment' including information as per your suggestions at Nanopore community website. It has been 2 days, I didn't receive any response. However, I am putting the information you asked below: 
Sample - Human lymphoblastoid cell line
Enzyme: DpnII;  
Read N50: 917
Contacts/GB: 176096.270877144
