### ISSUE TITLE
Generation of mandatory 3D-DNA input files

### ISSUE THREAD

**Issue by bistace** [nanoporetech/Pore-C-Snakemake#5]
Hi,

I successfully ran all the Snakemake pipeline to the end and generated the Salsa2 beds. I would now like to compare the results I got with Salsa2 to a 3D-DNA scaffolding. 3D-DNA wants a 'merged_nodups.txt" file generated by the juicer tools as input. Do you know if it would be possible to generate this file by using the ones generated by the PoreC pipeline?

**Comment by nhartwic** [comment]
Old issue, but thought I'd offer help if you still need it or for anyone coming to this issue.

Basically, you need to convert the medium style juicer output to the longform style output expected by 3ddna. I wrote a quick script to do this. You could probably come up with an awk 1 liner if you prefer...

https://gitlab.com/NolanHartwick/bio_utils/-/blob/master/juicer_med2long.py

The script needs pandas, just FYI. Also worth noting that while output from this script will work with 3ddna, at least as of November 2020, it leaves out a lot of information that really should be in the "merged_nodups.txt" file. Fortuantely, 3ddna doesn't seem to use these fields... yet.

**Comment by bistace** [comment]
Hi and thank you for providing a way to do this! I will test it in the coming days.

**Comment by eharr** [comment]
@nhartwic thanks so much for this script. There is now a command in pore_c tools to export to merged_no_dups (`pore_c contacts export`), though it includes some of the fields that 3dDNA doesn't use, so the file is likely to be quite a bit bigger.
