### ISSUE TITLE
Pore-C-Snakemake test run

### ISSUE THREAD

**Issue by molecule53** [nanoporetech/Pore-C-Snakemake#53]
Hi, 

I am trying out Pore-C-Snakemake with the test data. I am running it on Amazon Elastic Compute Cloud. It has been running for about 24 hrs and remains on "Creating conda environment envs/cooler.yml...Downloading and installing remote packages."  

(pore-c-snakemake) ubuntu@ip-172-31-25-247:/Data1/Pore-C-Snakemake$ snakemake --use-conda  test -j 4 --config=output_dir=results.test
Building DAG of jobs...
Creating conda environment envs/pore_c.yml...
Downloading and installing remote packages.
Environment for envs/pore_c.yml created (location: .snakemake/conda/227bd01d)
Creating conda environment envs/cooler.yml...
Downloading and installing remote packages.

<img width="1463" alt="Screen Shot 2023-03-23 at 10 27 01 AM" src="https://user-images.githubusercontent.com/128717253/227236021-fca60303-0c77-4bff-9114-d051797def27.png">

<img width="1078" alt="Screen Shot 2023-03-23 at 10 27 58 AM" src="https://user-images.githubusercontent.com/128717253/227236125-43435495-88b5-478c-a04c-575a12df8b86.png">

**Comment by eharr** [comment]
This pipeline has been deprecated - please use the new one at: https://github.com/epi2me-labs/wf-pore-c

**Comment by molecule53** [comment]
Hello,

Is there a test run I can do first?
I tried:

(base) ***@***.***:~$ ./nextflow run epi2me-labs/wf-porec --ubam test_data/porec_test.concatemers.bam --ref test_data/porec_test.genome.fasta --mcool_resolutions 10,20,30

N E X T F L O W  ~  version 22.10.7

Pulling epi2me-labs/wf-porec ...

WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/epi2me-labs/wf-porec/contents/nextflow.config

Remote resource not found: https://api.github.com/repos/epi2me-labs/wf-porec/contents/main.nf



(base) ***@***.***:~$ ls

miniconda3  nextflow  output  screenlog.0  snap  work


Best,
Anastasia

________________________________
From: Eoghan Harrington ***@***.***>
Sent: Thursday, March 23, 2023 11:03 AM
To: nanoporetech/Pore-C-Snakemake ***@***.***>
Cc: McKinlay, Anastasia ***@***.***>; Author ***@***.***>
Subject: [External] Re: [nanoporetech/Pore-C-Snakemake] Pore-C-Snakemake test run (Issue #53)

This message was sent from a non-IU address. Please exercise caution when clicking links or opening attachments from external sources.


This pipeline has been deprecated - please use the new one at: https://github.com/epi2me-labs/wf-pore-c

**Comment by eharr** [comment]
Can you please open an issue on the other repo - they'll be able to support you better.
