### ISSUE TITLE
Extracting info from .read.paraquet

### ISSUE THREAD

**Issue by callumparr** [nanoporetech/Pore-C-Snakemake#7]
I am interested to know the frequency of contacts per read. Can this information be extracted from he .read.paraquet file ? How can I read this? It seems to be some binary file.

**Comment by sachingadakh** [comment]
Run this python script with your files,
import pandas as pd
df = pd.read_parquet('DpnII_run01_hg38.fa.gz.at.overlap.parquet')
df.to_csv('DpnII_run01_hg38.fa.gz.at.overlap.pa.csv')

**Comment by callumparr** [comment]
Thank you for this. Sorry late reply.
