### ISSUE TITLE
Snakemake error

### ISSUE THREAD

**Issue by erbon7** [nanoporetech/Pore-C-Snakemake#8]
Hi

I've installed the conda environment and github code according to the instructions, but when I'm trying to run the test with 
snakemake --use-conda -d .test all

I have the following error:
Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	add_refgenome
	1	align_bwa
	1	all
	1	bwa_index_refgenome
	1	create_alignment_table
	1	create_base_cooler_file
	1	create_base_matrix
	1	create_mcool_file
	1	create_pairs_file
	1	import_basecalls
	1	virtual_digest
	11

[Sat Sep 19 19:50:11 2020]
rule add_refgenome:
    input: resources/GRCh38.fasta.gz
    output: results/refgenome/GRCh38.rg.catalog.yaml, results/refgenome/GRCh38.rg.metadata.csv, results/refgenome/GRCh38.rg.chromsizes, results/refgenome/GRCh38.rg.fa.gz, results/refgenome/GRCh38.rg.fa.gz.fai
    log: results/logs/results/refgenome/GRCh38.rg.catalog.yaml.log
    jobid: 1
    benchmark: results/benchmarks/results/refgenome/GRCh38.rg.catalog.yaml.bench.txt

[Sat Sep 19 19:50:12 2020]
Error in rule add_refgenome:
    jobid: 1
    output: results/refgenome/GRCh38.rg.catalog.yaml, results/refgenome/GRCh38.rg.metadata.csv, results/refgenome/GRCh38.rg.chromsizes, results/refgenome/GRCh38.rg.fa.gz, results/refgenome/GRCh38.rg.fa.gz.fai
    log: results/logs/results/refgenome/GRCh38.rg.catalog.yaml.log (check log file(s) for error message)
    shell:
        set +u; source ~/miniconda3/etc/profile.d/conda.sh ; conda activate ; conda activate poreC;  pore_c refgenome catalog resources/GRCh38.fasta.gz results/refgenome/GRCh38.rg --genome-id GRCh38 2> results/logs/results/refgenome/GRCh38.rg.catalog.yaml.log
        (exited with non-zero exit code)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Volumes/Samsung_T5/proj/Pore-C-Snakemake/.test/.snakemake/log/2020-09-19T195009.851034.snakemake.log

**Comment by eharr** [comment]
Hi @erbon7 - can you attach the contents of `results/logs/results/refgenome/GRCh38.rg.catalog.yaml.log`?

**Comment by erbon7** [comment]
Dear Eoghan, thanks for your reply. The log file has only one entry:
/bin/bash: pore_c: command not found

But I also installed the pore_c package from git according to the instruction.
I'm launching the snakemake command from the conda "pore_c_snakemake" environment.

**Comment by eharr** [comment]
It seems like something went wrong when creating the `poreC` conda environment. Just to double-check, would you mind trying the following commands in a new shell session:
```bash
conda activate poreC
pore_c --help
```

**Comment by erbon7** [comment]
Weird. Seems like pore_c is available in the snakemake environment but not in the poreC:

`(PoreC) erdos:Pore-C-Snakemake eric$ pore_c --help
-bash: pore_c: command not found
(PoreC) erdos:Pore-C-Snakemake eric$ conda deactivate
(base) erdos:Pore-C-Snakemake eric$ conda activate pore_c_snakemake
(pore_c_snakemake) erdos:Pore-C-Snakemake eric$ pore_c --help
Usage: pore_c [OPTIONS] COMMAND [ARGS]...

  Pore-C tools

  A suite of tools designed to analyse Oxford Nanopore reads with multiway
  chromatin contacts.

Options:
  -v, --verbosity  Increase level of logging information, eg. -vvv
  --quiet          Turn off all logging
  --help           Show this message and exit.

Commands:
  refgenome   Pre-process reference genome files.
  reads       Analyse raw reads
  alignments  Analyse aligned porec reads
  pairs       Create pairs files
  matrix      Operations on matrices
  dashboard   Dashboard`

**Comment by eharr** [comment]
Hmm - that is weird. It should be fixable with:
```
conda activate PoreC
pip install -e <path_to_pore-c_repo>
```

**Comment by eharr** [comment]
@erbon7 in case this didn't fix your issue there's a new version of the pipeline that simplifies the installation of pore-c tools.
