### ISSUE TITLE
Execution on slurm scheduler

### ISSUE THREAD

**Issue by antarikshtyagi** [nanoporetech/Pore-C-Snakemake#9]
Hello,

Can you please give instructions to run a job on sbatch?
I have just two files so do not need a lot of jobs, but want to use 36 cores and 2 days of runtime.

Thanks
Ant

**Comment by eharr** [comment]
Hi Ant,

I have no experience with slurm, so I'm afraid I can't help you. Snakemake handles all of the interaction with cluster queuing commands, so their documentation might have more info for you: https://snakemake.readthedocs.io/en/stable/executing/cli.html#profiles. 

All the best,
Eoghan

**Comment by antarikshtyagi** [comment]
Thanks Eoghan
